title: Sandro Huaman # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Bachelor in Mining Engineering 
  <br><br>
  Drilling and Blasting | Deep Learning  
  <br><br>
  <a href="https://www.linkedin.com/in/sandro-huaman/">Agregame a tu red de Linkedin</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
